### ISSUE TITLE
Notification is not received when app is in killed mode for specific device: Meizo Pro 7

### ISSUE THREAD

**Issue by kavathiyamahesh** [infobip/mobile-messaging-sdk-android#10]
Hello team,

I can able to receive notifications on other devices like Samsung S8, One plus, Pixels etc, but I can't able to receive notifications on **Meizo Pro 7**.

If application status is foreground then notification works fine.
Let me know if you need more help in this case.

Thanks.

**Comment by tjuric** [comment]
Hi @kavathiyamahesh ,
Can you check on the Meizu Pro 7 phone if background processing is enabled for your application? It seems to me that it isn't enabled on device.

Try with the following (starting from step 2):
https://austinmarton.wordpress.com/2017/01/08/meizu-flyme-notifications-fix/

**Comment by tjuric** [comment]
@kavathiyamahesh did you try the above solution? If not, here is one more tutorial to check up (this one is for WhatsApp app but you should be able to apply it for your application): https://forum.xda-developers.com/meizu-pro-5/how-to/tutorial-make-notifications-flymeos-t3456733. 

Please, update us on the progress

**Comment by stanislavin** [comment]
We can also suggest to try out same use-case with our demo application: https://play.google.com/store/apps/details?id=com.infobip.pushdemo
The behaviour should not be related to the SDK or your implementation, but is a general device policy.

**Comment by jayeshthadani** [comment]
Hi @stanislavin :  In Meizu Pro 7 device, there are 3 options for Run in background as 1) Smart Background (recommended) 2) Allow running in background 3) Disallow. 
by default 1) Smart background option is selected, But we don't receive PN if application is not running in background. 

However changing option to 2) Allow running in background, We receive PN for application irrespective app running in background or not. 

It seems that Meizu devices have some logic set but that doesn't work correctly with PN.

**Comment by tjuric** [comment]
Hi @jayeshthadani,

We're aware of "Smart background" mode and battery saver/power management apps. However, these issues are out of our responsibility and we can only advise you on approaches and methods of what you might do on those devices to receive notifications regularly.

Even if you had pure Firebase implementation of push (without our SDK) you'd get the same output. The only people who can manage these options on some Android phones are end users. 
However, you might add additional logic to your app - inform your users once with some in-app message about required running in background (if it is required for the app) and enabled app notifications for better user experience.   

As you stated, push notifications **are** received when background running is allowed, so I'd consider this as solved.

**Comment by jayeshthadani** [comment]
Hi @tjuric , Thanks for reply. 

We have verified scenario with few other OEMs like Vivo on device model : Vivo V9 Pro.
Result: We don't receive push notification on Vivo device as well when app is not running in background and there is no other option as well like in Meizu device. 
Does it mean that push notification will not work in OEM like Vivo ?
Kindly don't close this ticket we need to investigate further in this.

**Comment by nsustavov** [comment]
Hi @jayeshthadani 
are you referring for the case with Vivo power management described here? 
https://www.vivo.com/en/support/questionByTitle?title=How%20to%20turn%20on/off%20High%20background%20power%20consumption?

as well there is an option to enable "autostart" in background and is placed OS App management settings.

**Comment by jayeshthadani** [comment]
Hi @nsustavov : There are lot of Chinese OEMs which override functionality of Android stock rom for power management. 
We have identified most common 5 OEMs like **Vivo, Oppo, huawei, xiaomi and meizu** in which PNs were not delivered if application is not in running mode. 
To overcome this issue we navigate App user to Power management setting of device to enable **Autostart or other similar setting** depending on OEM. 

This issue is handled with our App now, and it is working fine. 

Improvement suggestion: Can this issue be fixed as part of Infobip - Android SDK ? Then it will be eliminate logic to be written on Android app.

**Comment by jayeshthadani** [comment]
As PN is working fine with additional logic on mentioned OEMs , we can close this ticket.

**Comment by nsustavov** [comment]
Hi Jayesh,
yes we have in our roadmap such improvement, though most probably it will be separate component or even SDK. Although the exact timing isn't yet defined. 
Once it comes out we'll post release notes. I'm closing the ticket for now.
