### ISSUE TITLE
personalize() callback not working when user register first time in infobip

### ISSUE THREAD

**Issue by kavathiyamahesh** [infobip/mobile-messaging-sdk-android#13]
Hello team, @tjuric @stanislavin 
I am facing one issue which is related to callback **onResult()** of **MobileMessaging.getInstance(context).personalize()** method.

I am initializing SDK using below code : 
```
MobileMessaging.Builder(context.applicationContext as Application)
                .withHttpSettings(true)
                .withDisplayNotification(NotificationSettings.Builder(context.applicationContext as Application)
                        .withMultipleNotifications()
                        .withDefaultIcon(R.drawable.ic_stat_notification)
                        .build())
                .build(object : MobileMessaging.InitListener{
                    override fun onSuccess() {
                     //AFTER SUCCESS OF SDK INITILISE, I HAVE TO SEND EXTERNAL ID TO INFOBIP PORTAL.
                        personalizeExternalPersonId("externalId")
                    }

                    override fun onError(e: InternalSdkError?, googleErrorCode: Int?) {
                       }
                })
```
On the success of Initialise SDK, I am calling personalizeExternalPersonId method for sending the external ID of the user:

```
private fun personalizeExternalPersonId(personId: String) {
        val userIdentity = UserIdentity()
        userIdentity.externalUserId = personId
        MobileMessaging.getInstance(context).personalize(userIdentity, null, object : MobileMessaging.ResultListener<User>() {
            override fun onResult(result: Result<User, MobileMessagingError>?) {
              //THIS CALL BACK IS NOT WORKING FIRST TIME WHEN USER REGISTER WITH INFOBIP, IF I KILL THE APP AND AGAIN INITIALISE SDK THEN THIS CALL BACK IS WORKING FINE AS EXPECTED.
            }
        })
    }
```
So, Personalize callback[onResult()] not working because of SDK is not initialize properly
**Note: If I put some delay for calling personalize method then the callback is working fine as expected. please find below working code.**

```
MobileMessaging.Builder(context.applicationContext as Application)
                .withHttpSettings(true)
                .withDisplayNotification(NotificationSettings.Builder(context.applicationContext as Application)
                        .withMultipleNotifications()
                        .withDefaultIcon(R.drawable.ic_stat_notification)
                        .build())
                .build(object : MobileMessaging.InitListener{
                    override fun onSuccess() {
                       // PLEASE FIND BELOW WORKING CODE
                        Handler().postDelayed({
                            personalizeExternalPersonId("externalId")    
                        },2000)
                    }
                    override fun onError(e: InternalSdkError?, googleErrorCode: Int?) {}
                })
```

I am using the latest Android SDK version: 2.0.15

Thanks

**Comment by tjuric** [comment]
Hi @kavathiyamahesh,

I see that you're using [InitListener](https://github.com/infobip/mobile-messaging-sdk-android/blob/master/infobip-mobile-messaging-android-sdk/src/main/java/org/infobip/mobile/messaging/MobileMessaging.java#L405-L422) in our lib to know when the init was done. 

This init just takes care of the smooth init progress, but it does not guarantee that the registration is created at that moment, just that the process has started. 

We have an event called [`REGISTRATION_CREATED`](https://github.com/infobip/mobile-messaging-sdk-android/wiki/Events#registration_created) that’s triggered on creating of new push reg id. You might do the personalization when this event is triggered.

As per non-working callback, currently it doesn't trigger if push registration ID doesn't exist, but we miss some error message. It will be tuned on our end.

Regards,
Tereza

**Comment by kavathiyamahesh** [comment]
Hello @tjuric 
Thanks for a quick response.
Ok, I will try by event, but I don't understand why we have to use the event as we already have a callback. Is it possible to doable via callback instead of broadcast event?

**Comment by kavathiyamahesh** [comment]
I just have a check via REGISTRATION_CREATED event thru broadcarst, event is triggered but Installation is receiving null from intent.

```
private inner class InfobipReceiver : BroadcastReceiver() {
        override fun onReceive(context: Context, intent: Intent) {
            val installation : Installation? = Installation.createFrom(intent.extras)
//GETTING INSTALLATION NULL, BUT I CAN SEE THERE IS NEW DEVICE ENTRY ON INFOBIP PORTAL.
        }
    }
```

How I can handle error scenario inside that broadcast event?

**Comment by kavathiyamahesh** [comment]
Hello, @tjuric @stanislavin any updates on this? Thanks

**Comment by tjuric** [comment]
Hi @kavathiyamahesh,

> I don't understand why we have to use the event as we already have a callback. Is it possible to doable via callback instead of broadcast event?

As I already said, this `InitListener` just takes care of the smooth init progress, but it does not guarantee that the registration is created at that moment, just that the process of acquiring has started. We might change this behaviour at some point, but it's not in our plans now.

> event is triggered but Installation is receiving null from intent

We've had an issue in our documentation. This event returns push registration ID as an extra and it can be fetched like this: 
`String pushRegistrationId = intent.getStringExtra(BroadcastParameter.EXTRA_INFOBIP_ID);`

> How I can handle error scenario inside that broadcast event?

All init errors with configuration (Play services unavailable) should be caught by InitListener `onError` method and our library is retrying with attempts to create a new registration on our backend in case there are some connection issues. You might listen to [`GOOGLE_PLAY_SERVICES_ERROR`](https://github.com/infobip/mobile-messaging-sdk-android/wiki/Events#google_play_services_error) or  [`API_COMMUNICATION_ERROR`](https://github.com/infobip/mobile-messaging-sdk-android/wiki/Events#api_communication_error) (API communication error can happen on any other API issue - it's a general listener, and probably there is no need to handle there anything).
Listening for `REGISTRATION_CREATED` event or relying on [registration ID not being empty](https://github.com/infobip/mobile-messaging-sdk-android/wiki/How-do-I-get-Infobip's-unique-(push-registration)-ID%3F) should be the starting point for further personalization.

**Comment by kavathiyamahesh** [comment]
Ok @tjuric 
Thanks for the information in depth, let me check with your solution and update you.

**Comment by kavathiyamahesh** [comment]
Hello @tjuric 
Can you please confirm, that REGISTRATION_CREATED will be not triggered if `onError` method calls while initializing the SDK.

**Comment by tjuric** [comment]
@kavathiyamahesh `REGISTRATION_CREATED` is triggered only when we get push registration ID the first time from our backend. So, yes - I can confirm.

Regards,
Tereza

**Comment by kavathiyamahesh** [comment]
@tjuric Thanks for the confirmation, We can close this issue and re-open if needed.

**Comment by tjuric** [comment]
Ok @kavathiyamahesh, closing the issue.
