### ISSUE TITLE
How to get and send tags in push notification android app.

### ISSUE THREAD

**Issue by tabassumLatif** [infobip/mobile-messaging-sdk-android#2]
Please tell me how to get and add tags  in push notification

**Comment by tjuric** [comment]
Setting tags:
```
Map<String, CustomUserDataValue> customDataMap = new HashMap<>();
CustomUserDataValue tagsValue = new CustomUserDataValue("tags");
customDataMap.put("funny", tagsValue);
customDataMap.put("cool", tagsValue);
customDataMap.put("interesting", tagsValue);

UserData userData = new UserData();
userData.setCustomUserData(customDataMap);

MobileMessaging.getInstance(this).syncUserData(userData);
```

Fetching them:
```
MobileMessaging.getInstance(getActivity()).fetchUserData(new MobileMessaging.ResultListener<UserData>() {
    @Override
    public void onResult(UserData userData) {
        ...
    }

    @Override
    public void onError(MobileMessagingError e) {
        ...
    }
});
```

Same examples can be found in our official wiki docs for [setting tags](https://github.com/infobip/mobile-messaging-sdk-android/wiki/User-data#using-custom-user-data-for-tagging-and-subscriptions) (as part of the user data) and [fetching them](https://github.com/infobip/mobile-messaging-sdk-android/wiki/User-data#fetching-user-data-from-the-server).

**Comment by tabassumLatif** [comment]
https://portal.infobip.com/people/tags
I add tags here.
this tag not return { "customUserData":{}, 
                                "externalUserId":null,
                                "predefinedUserData":{}
                              }

**Comment by tjuric** [comment]
Creating tags on our customer portal (CUP) and using them later on in the app isn't currently supported. What you can do is manage tags through the API provided in SDK, and use those tags when targeting people.
