### ISSUE TITLE
Can you provide migration guide from 2.x to 3.x versions of the SDK?

### ISSUE THREAD

**Issue by finchatticus** [infobip/mobile-messaging-sdk-android#21]

**Comment by tjuric** [comment]
Hi @finchatticus,
We updated release notes of 3.0.0 version with the description: https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/3.0.0.

In short:
- Reimport classes `MobileMessagingError` and `Result` (package name changed):
  * old: `import org.infobip.mobile.messaging.mobile.MobileMessagingError;`, new: `import org.infobip.mobile.messaging.mobileapi.MobileMessagingError;`
  * old: `import org.infobip.mobile.messaging.mobile.Result;`, new: `import org.infobip.mobile.messaging.mobileapi.Result;`
- If you used previous chat module, it's completely rewritten and if used should be newly implemented by following guidelines provided [here](https://github.com/infobip/mobile-messaging-sdk-android/wiki/In%E2%80%90app-chat)

Best regards,
Tereza
