### ISSUE TITLE
Infobip SDK create new InstanceId on activation

### ISSUE THREAD

**Issue by jayeshthadani** [infobip/mobile-messaging-sdk-android#24]
Hello, 

We are using Infobip SDK library as v2.2.1 & we have defined FCM lib as v17.3.4 in our base project.

To improve, we upgrade FCM lib to v20.1.0 which is higher version than older 17.3.4.
After this change, When we activate Infobip push notification, App generates new Firebase Instance Id for project & possibly token as well. 

Firebase Instance Id is important information on our app as App's unique identifier depends on this.
Can you try to reproduce issue on Infobip, if Firebase's deleteInstanceId or deleteToken get's executed when FCM 20.1.0 is used ?

TIA.

**Comment by tjuric** [comment]
Hi @jayeshthadani,

Could you tell us if there is any specific reason you're using version 2.2.1 of our SDK? It's pretty outdated and we did have some [issues](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/2.2.1) related to it. I'd suggest you to update to our latest SDK version 4.3.1, migration shouldn't be hard https://github.com/infobip/mobile-messaging-sdk-android/wiki/Migration-guide. 

We don't invoke by ourselves `deleteInstanceId` in our code, so Firebase's instance ID shouldn't be deleted by our library. Firebase-messaging v20.1.0 is using Android X packages and we need to update it. We intend to update firebase-messaging package in close future. 

Best regards,
Tereza

**Comment by jayeshthadani** [comment]
Hi @tjuric : I just verified result by updating Infobip lib v4.3.1 and seems issue is fixed with it. No new InstanceId created after enabling push notification with Infobip.

We are using v2.2.1 and did not migrated to latest v4.x since our requirement so far suffice with v2.2.1. 
By the way, can you tell me which FCM version is used in Infobip's v4.3.1 ?

**Comment by tjuric** [comment]
Version 17.6.0 is used in 4.3.1. We plan to migrate to 21.x, but no strict ETA yet when will it be done.
Issue with 2.2.1 version is that it was using GCM library instead of FCM - that might be the issue that you faced.

BR,
Tereza

**Comment by jayeshthadani** [comment]
I have still used FCM v20.1.0 and Infobip - 4.3.1. Technically Android takes higher version if same lib claimed by different libs/sdk. So project takes FCM v20.1.0 in current case.
I will update results of Instance Id when FCM v20.1.0 and Infobip v2.2.1 is used.

**Comment by tjuric** [comment]
Hi @jayeshthadani,
Do you need any assistance from our side about this tissue?

**Comment by jayeshthadani** [comment]
On upgrading Infobip to 4.3.1, issue is fixed. Thanks for assistance. Appreciated !!
