### ISSUE TITLE
Mobiburn sdk in Infobip v4.3.1 for Android

### ISSUE THREAD

**Issue by jayeshthadani** [infobip/mobile-messaging-sdk-android#25]
Hello, 
Recently our app got rejected on Play store - given a reason that Play store found Mobiburn SDK used. 
Mobiburn extract few PII information and it's banned from use from Android app.

I couldn't find any evidence of Mobiburn sdk by checking dependency graph, but latest update have just implemented update of Infobip sdk. So just a quick check if Infobip is using Mobiburn for any reason?

**Comment by tjuric** [comment]
Hi @jayeshthadani,

Aside official Firebase and Google libraries, we use only GSON and Common codec libraries. Here you can see list of them:
https://github.com/infobip/mobile-messaging-sdk-android/blob/master/infobip-mobile-messaging-api-java/build.gradle#L83-L84
https://github.com/infobip/mobile-messaging-sdk-android/blob/master/infobip-mobile-messaging-android-sdk/build.gradle#L45-L50

We never used Mobiburn SDK in any form.
