### ISSUE TITLE
Unsafe Cipher mode in org.infobip.mobile.messaging.util.Cryptor

### ISSUE THREAD

**Issue by devmike01** [infobip/mobile-messaging-sdk-android#26]
I tried updating my company's app on the playstore and ended up with the below error, and the app was rejected. This is happening on  `infobip-mobile-messaging-android-sdk:5.0.1'`

Unsafe Cipher Mode
error
Error
Security

Your app contains a less secure encryption mode. Please see this Google Help Center article for details.

    org.infobip.mobile.messaging.util.Cryptor.Ι

**Comment by riskpp** [comment]
Hi @OGx09, in 5.0.0 version we've migrated from ECB encryption mode to CBC encryption, which is [recommended by google](https://developer.android.com/guide/topics/security/cryptography#choose-algorithm).

`org.infobip.mobile.messaging.util.Cryptor` it's abstract class with two implementations, 1st is for CBC encryption - [CryptorImpl.java](https://github.com/infobip/mobile-messaging-sdk-android/blob/master/infobip-mobile-messaging-android-sdk/src/main/java/org/infobip/mobile/messaging/util/CryptorImpl.java) and 2nd [ECBCryptorImpl](https://github.com/infobip/mobile-messaging-sdk-android/blob/master/infobip-mobile-messaging-android-sdk/src/main/java/org/infobip/mobile/messaging/util/ECBCryptorImpl.java) is deprecated and used only to migrate previously saved data.

Could you please send the article, on which google is referring, just in case.

BR,
Olga

**Comment by devmike01** [comment]
Here it is https://support.google.com/faqs/answer/10046138 . Also, I have since updated the library's version to `5.2.1` which is currently the latest version.

**Comment by OGx09** [comment]
I have updated the library to the latest version and yet I got a warning that the library contains less secure encryption mode. 

You can find the affected function below.

`org.infobip.mobile.messaging.util.ECBCryptorImpl.encodeAES128`

**Comment by riskpp** [comment]
Hi @OGx09,

You may answer this to Google:
"Mobile Messaging SDK migrated from ECB encryption to CBC encryption as recommended by Google. Cryptor implementation from class `org.infobip.mobile.messaging.util.ECBCryptorImpl` is deprecated and used only to migrate previously saved data."

We will try to invent something from our side, if it will not satisfy them.

Just to notice, we've released our [application to Google Play](https://play.google.com/store/apps/details?id=com.infobip.pushdemo) recently without rejection.

BR, Olga

**Comment by devmike01** [comment]
Hi Olga, I have reached out to Google Play support team but they're yet to respond.

**Comment by devmike01** [comment]
Hi @riskpp , this issue has been resolved. Thank you
