### ISSUE TITLE
Do you have a flutter plugin? 

### ISSUE THREAD

**Issue by RoySis** [infobip/mobile-messaging-sdk-android#27]
Do you have a flutter plugin? I didn't find it in the documentation.

**Comment by riskpp** [comment]
Hi @RoySis, we don't have flutter support now, but we have it in the nearest plans.

Now we have [Cordova](https://github.com/infobip/mobile-messaging-cordova-plugin) and [React-Native](https://github.com/infobip/mobile-messaging-react-native-plugin) plugins.

BR, Olga

**Comment by riskpp** [comment]
Hi @RoySis, recently we've released flutter plugin - https://github.com/infobip/mobile-messaging-flutter-plugin

BR, Olga
