### ISSUE TITLE
Android 12 - Notifications tap error ( Indirect notification activity start )

### ISSUE THREAD

**Issue by carealejo** [infobip/mobile-messaging-sdk-android#29]
Hi, 

Using version 5.3.6

Currently working on Android 12 ( SDK 31 ) we are available to get notifications but the notification doesn't do any action after tap on it.

The new updates for Android 12 can't start activities from services or broadcast receivers ( https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines )

Do you have any fix for Android 12 or any change we can do to support this new restriction?

**Comment by riskpp** [comment]
Hi, @carealejo,
We are working on major SDK release for support of Android 12 and target/compile versions 31. It'll be available at the end January.
For now you can use target/compile versions 30.

BR,
Olga

**Comment by riskpp** [comment]
Hi @carealejo, we've released [6.0.0-rc](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/6.0.0-rc1) version with Android 12 support.

1. Only core functionality supported in this release (in-app chat and geo modules aren't available)
2. [Migration Guide](https://github.com/infobip/mobile-messaging-sdk-android/wiki/Migration-guide#migration-from-5x-to-6x-rc)
3. [Quick start guide](https://github.com/infobip/mobile-messaging-sdk-android/tree/release_6.0.0#mobile-messaging-sdk-for-android)
3. [Applying Firebase configuration in MobileMessaging SDK Guide](https://github.com/infobip/mobile-messaging-sdk-android/wiki/Applying-Firebase-configuration-in-MobileMessaging-SDK)

**Comment by rajdamani** [comment]
Hello @riskpp - what is the plan for releasing the SDK with Android 12 support?

**Comment by riskpp** [comment]
Hello @rajdamani, we are working on it, release expected in beginning of February. I'll inform in this thread.

**Comment by rajdamani** [comment]
> Hello @rajdamani, we are working on it, release expected in beginning of February. I'll inform in this thread.

Hi @riskpp - Just so we can plan on our app release, do you have a tentative date for the release with this fix?

**Comment by riskpp** [comment]
Hello @rajdamani, we will have release not later than 15th of Feb, but today we've released [6.0.0-rc2](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/6.0.0-rc2) with all functionality supported, you can start with it, could be that migration from your side is needed - [Migration from 5.x to 6.x](https://github.com/infobip/mobile-messaging-sdk-android/wiki/Migration-guide#migration-from-5x-to-6x)

**Comment by riskpp** [comment]
[6.0.0 version](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/6.0.0) released. Notification tap and other things related to Android 12 should be fine now. Feel free to open issue, if not.

**Comment by rajdamani** [comment]
Thanks @riskpp - I will start migrating our app to 6.0.0.
