### ISSUE TITLE
How can I hide the conversation icon ?

### ISSUE THREAD

**Issue by rhenanfaria** [infobip/mobile-messaging-sdk-android#30]
Hello guys - I need to setup the Infobip Live Chat for both iOS and Android devices,  I setup the javascript Infobip Livechat in my App (Android and iOS), and I was able to call the chat properly, the only caveat is that once I hit to close the conversation box, a baloon shaped icon is kept in my app screen, which is no good for the end-user perspective. (this baloon overlaps other functionalities)

Infobip team told me that is not possible to remove this icon with the resource I am using (javascript) then they asked me to use SDK for this purpose, which would give me more flexibility to hide the baloon button.

The question is, how can I disable this icon using SDK, I´m not a programmer, sorry if this question is too simple, I am trying to deep dive the way to set it up and convey this information ahead for the development team

Thanks in advance!

**Comment by alboldy-ib** [comment]
Hello,

To use in-app chat inside your mobile application SDK must be already integrated. Can you share which SDK or plugin version you used to integrate with your application, along with a screenshot of the bubble in question?

The documentation on in-app chat is available on wiki - https://github.com/infobip/mobile-messaging-sdk-android/wiki/In%E2%80%90app-chat#display-in-app-chat-view

**Comment by rhenanfaria** [comment]
Hi Alexander - thank you for your prompt response:

Here follows the first fragment, with the on click action and the Chat Live button that is displayed in the screen, I removed the credential for security purposes, this mechanism works fine, so far so good.

`<div onclick="(function(){liveChat('init', 'KEY HERE!');})()" role="button" tabindex="0" style="margin: 1px; padding: 0px; border-style: solid; border-width: 0px; font-style: normal; font-weight: normal; font-variant: normal; list-style: outside none none; letter-spacing: normal; line-height: normal; text-decoration: none; vertical-align: baseline; white-space: normal; word-spacing: normal; background-repeat: repeat-x; background-position: left bottom; background-color: transparent; border-radius: 10px; width: 240px; height: 125px; cursor: pointer; display: block; position: relative; top: 0px; left: 0px;">
<img src="CHAT-ONLINE.PNG" style="margin: 0px; padding: 0px; border-style: none; border-width: 0px; font-style: normal; font-weight: normal; font-variant: normal; list-style: outside none none; letter-spacing: normal; line-height: normal; text-decoration: none; vertical-align: baseline; white-space: normal; word-spacing: normal; position: absolute; top: -5px; left: -6px; z-index: 600;"></div>`

The fragment bellow is the Infobip Chat live being rendered in the App Screen, this rendering is fine.

`<div class="ib-widget-wrapper" style="bottom: 100px; right: 20px; background-position: center center; background-repeat: no-repeat; background-color: rgb(255, 255, 255); visibility: visible; z-index: 21370001;" data-gainsight-id="livechat-widget"><div class="ib-close-mobile-button" style="background-image: url(&quot;data:image/svg+xml;utf8,<svg xmlns=\&quot;http://www.w3.org/2000/svg\&quot; width=\&quot;60\&quot; height=\&quot;60\&quot; viewBox=\&quot;0 0 60 60\&quot;>
<path d=\&quot;M0 0h24v24H0z\&quot; fill=\&quot;none\&quot;/><path transform=\&quot;translate(18,18)\&quot; d=\&quot;M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z\&quot; fill=\&quot;%23ffffff\&quot;/></svg>&quot;); height: 48px; width: 48px; fill: rgb(0, 122, 188); background-size: cover;"></div><iframe id="ib-iframe-messaging" src="https://livechat.infobip.com/widget.html" style="background-color: rgb(255, 255, 255); display: block;"></iframe></div>`

And finally, the fragment bellow is the bubble icon that apears and I am not able to hide it, here I have an issue.

`<div id="ib-button-messaging" style="background-color: rgb(0, 122, 188); bottom: 20px; right: 20px; display: flex;"><div id="ib-button-messaging-icon" style="background-image: url(&quot;data:image/svg+xml;utf8,<svg xmlns=\&quot;http://www.w3.org/2000/svg\&quot; width=\&quot;60\&quot; height=\&quot;60\&quot; viewBox=\&quot;0 0 60 60\&quot;><path d=\&quot;M0 0h24v24H0z\&quot; fill=\&quot;none\&quot;/><path transform=\&quot;translate(18,18)\&quot; d=\&quot;M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z\&quot; fill=\&quot;%23ffffff\&quot;/></svg>&quot;); height: 60px; width: 60px; border-radius: 50%; fill: rgb(0, 122, 188); background-size: cover;"></div><div id="ib-unread-messages-counter-bubble" class="ib-widget-unread-messages-bubble" style="visibility: hidden;"><span id="unread-message-counter" class="ib-widget-unread-message-counter" style="color: rgb(255, 255, 255);">0</span></div></div>`

Here follows an screenshot of the App, see the bubble in the bottom of the screen

![image](https://user-images.githubusercontent.com/103588105/163242685-a69feb23-53e2-4e42-bd56-bbdfd2d2f47d.png)

**Comment by riskpp** [comment]
Hi @rhenanfaria, there is a big difference between integrating in-app chat for mobile browsers and integration it inside the mobile application.
Please, check live chat docs for mobile applications - https://www.infobip.com/docs/live-chat/getting-started#mobile-in-app-chat
If you integrate in-app chat inside the mobile applications, by using mobile sdks, conversation icon won't appear at all.

**Comment by rhenanfaria** [comment]
Thank you so much Olga.

**Comment by riskpp** [comment]
Closing, because seems it's solved
