### ISSUE TITLE
SDK_ERROR, 20006, There is no valid registration

### ISSUE THREAD

**Issue by Demetresko** [infobip/mobile-messaging-sdk-android#33]
Hello, our project contains infobip message services and on some devices like samsung g950-f Android 9,  app constantly gets this error SDK_ERROR, 20006, There is no valid registration. 
This is how library is initialised:

MobileMessaging.Builder(application)
            .withDisplayNotification(
                NotificationSettings.Builder(application)
                    .withDefaultTitle(getString(R.string.common_app_name))
                    .withCallbackActivity(MainActivity::class.java)
                    .build()
            ).build()

Can you tell, where is possible problem can be ?

**Comment by tjuric** [comment]
Hi @Demetresko,
Init code looks good. Library should be able to make a new push registration when FCM token gets generated. You could find this in docs as well https://github.com/infobip/mobile-messaging-sdk-android/wiki/Troubleshooting#i-see-errors-in-logcat-what-do-they-mean.

Could you share with us if you have any logs in the LogCat related to Firebase and token?

**Comment by Demetresko** [comment]
@tjuric  here what log shows 

V/MobileMessaging: FirebaseRegistrationTokenHandler
    [
      "RECEIVED FCM TOKEN",
      [
        "dJXT4RgbQ_--vLIV8uM2aN:APA91bEZ0KBWQBWtlkMULnk9hBfFQhSSV1BcOUCSXjsbswvmk0EJy9_mVcEjHKCkjfsj7zGIaCLb_n5yeFiVPBkF2faaik5oJjWfjV8bOxZaVNwq1XdPy2HlUSfLh8piL97RQlOW4-fq"
      ]
    ]

**Comment by tjuric** [comment]
Looks like library is able to get the token from FCM. Maybe networking request is failing for some reason.

Can you subscribe to broadcast even `REGISTRATION_CREATED` and check if it's ever invoked? And check if the push registration ID is logged like here https://github.com/infobip/mobile-messaging-sdk-android/wiki/How-do-I-get-Infobip's-unique-(push-registration)-ID%3F.

Can you share with us:
- logs with `MobileMessaging` tag (hide sensitive data, please or send it to our support on support@infobip.com with the link to this ticket)
- SDK version
- OS version

**Comment by Demetresko** [comment]
```xml 
<receiver android:name="ru.bspb.b2b.receiver.InfobipMessageReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="org.infobip.mobile.messaging.MESSAGE_RECEIVED"/>
            </intent-filter>
            <intent-filter>
                <action android:name="org.infobip.mobile.messaging.REGISTRATION_CREATED"/>
            </intent-filter>
</...>
```

```java
  override fun onReceive(context: Context, intent: Intent) {
        DaggerBroadcastReceiverComponent.builder()
            .infobipMessageModule(InfobipMessageModule(context))
            .build().injectInfobipBroadcastReceiver(this)
        if (Feature.PUSH_STORE.defaultState == FeatureState.ENABLED) {
            val result = goAsync()

            when (intent.action) {
                Event.TOKEN_RECEIVED.key -> {
                    val token =
                        intent.getStringExtra(BroadcastParameter.EXTRA_CLOUD_TOKEN) ?: return
                    Lc.d(TAG, "got token: $token")
                }
            }
```
SDK version 6.3.2
OS version Android 9.0

**Comment by tjuric** [comment]
Hi @Demetresko,
You didn't provide us logs from LogCat. 

Please, report this issue to our support e-mail with logs with MobileMessaging tag to [support@infobip.com](mailto:support@infobip.com) providing the link to this ticket.

Push registration ID should be generated if token exists. 

Did you try to make a clean install of the app and you still receive this issue?

**Comment by Demetresko** [comment]
Here is my result object when device fetches installation, yes I tried to install app on a clean device, it didnt help however.

appVersion = ""
applicationUserId = null
deviceManufacturer = ""
deviceModel = ""
deviceName = ""
deviceSecure = {Boolean@22457} false
deviceTimezoneOffset = ""
geoEnabled = {Boolean@22457} false
isPrimaryDevice = {Boolean@22457} false
isPushRegistrationEnabled = {Boolean@22458} true
language = ""
notificationsEnabled = {Boolean@22458} true
os = "Android"
osVersion = ""
pushRegistrationId = null
pushServiceToken = "ebdvShTPTK-xGZMcdLACrr:APA91bFzNHssQw8jPYiMcrCcQNFcUagiwl5KosHJrY7x7MAyRAm765qCxmUQoM0SLOJd1mdQR5iLORJaLbamvPiTTxxsuEUbf-jzC9UbbNyt3I86ewY33yvtEC6F0oDY5gFJZ9NOZPxo"
pushServiceType = {Installation$PushServiceType@22461} "Firebase"
sdkVersion = "6.3.2"
customAttributes = {HashMap@22463}  size = 0
map = {HashMap@22464}  size = 0
shadow$_klass_ = {Class@15291} "class org.infobip.mobile.messaging.Installation"
shadow$_monitor_ = 0

**Comment by riskpp** [comment]
Hi @Demetresko, looks like it's the issue with the certificate on the device, it's expired (from the logs, which we received via e-mail) and all networking requests are failed

**Comment by Demetresko** [comment]
The problem doesnt occur on other devices where application gets same Certificate Expired error.
{
      "cancelled": false,
      "error": {
        "code": "-4",
        "cause": {
          "cause": {
            "cause": {
              "detailMessage": "Certificate expired at Thu May 12 12:19:55 GMT+03:00 2022 (compared to Wed Sep 14 12:03:15 GMT+03:00 2022)",
              "stackTrace": [],
              "suppressedExceptions": []
            },
            "detailMessage": "Unacceptable certificate: C\u003dNZ, ST\u003dAuckland, L\u003dAuckland, O\u003dXK72 Ltd, OU\u003dhttps://charlesproxy.com/ssl, CN\u003d\"Charles Proxy CA (13 May 2021, MacBook-Pro-Dimitriy.local)\"",
            "stackTrace": [],
            "suppressedExceptions": []
          },
          "detailMessage": "Unacceptable certificate: C\u003dNZ, ST\u003dAuckland, L\u003dAuckland, O\u003dXK72 Ltd, OU\u003dhttps://charlesproxy.com/ssl, CN\u003d\"Charles Proxy CA (13 May 2021, MacBook-Pro-Dimitriy.local)\"",
          "stackTrace": [],
          "suppressedExceptions": []
        },
        "detailMessage": "Can\u0027t access URI : https://mobile.infobip.com/mobile/1/baseurl",
        "stackTrace": [],
        "suppressedExceptions": []
      },
      "inputs": []
    }

but after this 

V/MobileMessaging: Result wrapper: 
    {
      "cancelled": false,
      "error": {
        "code": "-4",
        "cause": {
          "cause": {
            "cause": {
              "detailMessage": "Certificate expired at Thu May 12 12:19:55 GMT+03:00 2022 (compared to Wed Sep 14 12:03:15 GMT+03:00 2022)",
              "stackTrace": [],
              "suppressedExceptions": []
            },
            "detailMessage": "Unacceptable certificate: C\u003dNZ, ST\u003dAuckland, L\u003dAuckland, O\u003dXK72 Ltd, OU\u003dhttps://charlesproxy.com/ssl, CN\u003d\"Charles Proxy CA (13 May 2021, MacBook-Pro-Dimitriy.local)\"",
            "stackTrace": [],
            "suppressedExceptions": []
          },
          "detailMessage": "Unacceptable certificate: C\u003dNZ, ST\u003dAuckland, L\u003dAuckland, O\u003dXK72 Ltd, OU\u003dhttps://charlesproxy.com/ssl, CN\u003d\"Charles Proxy CA (13 May 2021, MacBook-Pro-Dimitriy.local)\"",
          "stackTrace": [],
          "suppressedExceptions": []
        },
        "detailMessage": "Can\u0027t access URI : https://mobile.infobip.com/mobile/1/baseurl",
        "stackTrace": [],
        "suppressedExceptions": []
      },
      "inputs": []
    }
2022-09-14 12:03:15.530 29954-29954/ru.bspb.b2b E/MobileMessaging: Error while checking base URL!
2022-09-14 12:03:15.592 29954-30339/ru.bspb.b2b V/MobileMessaging: CREATE INSTALLATION >>>
    {
      "appVersion": "8.3.2451.debug",
      "deviceManufacturer": "Google",
      "deviceModel": "AOSP on IA Emulator",
      "deviceName": "AOSP on IA Emulator",
      "deviceSecure": false,
      "deviceTimezoneOffset": "GMT+03:00",
      "geoEnabled": false,
      "language": "en",
      "notificationsEnabled": true,
      "os": "Android",
      "osVersion": "9",
      "pushServiceToken": "e4Wwqa3KTieMjPLElDbhCt:APA91bH9EPrEGZJl5yqEn3AU-1vTGYdPoefcD6XcUgx-GapjDywxsvZpLqUk16EYf-PM1hs5idD1LPQ0WO7i6ftoy1OADELPxyhznyuONw6T0eMQcGVNiJSPTuMxU4eDdCjn14aGdwBt",
      "pushServiceType": "Firebase",
      "sdkVersion": "6.3.2",
      "map": {
        "appVersion": "8.3.2451.debug",
        "os": "Android",
        "geoEnabled": false,
        "pushServiceToken": "e4Wwqa3KTieMjPLElDbhCt:APA91bH9EPrEGZJl5yqEn3AU-1vTGYdPoefcD6XcUgx-GapjDywxsvZpLqUk16EYf-PM1hs5idD1LPQ0WO7i6ftoy1OADELPxyhznyuONw6T0eMQcGVNiJSPTuMxU4eDdCjn14aGdwBt",
        "notificationsEnabled": true,
        "language": "en",
        "deviceName": "AOSP on IA Emulator",
        "pushServiceType": "Firebase",
        "osVersion": "9",
        "deviceTimezoneOffset": "GMT+03:00",
        "deviceSecure": false,
        "sdkVersion": "6.3.2",
        "deviceModel": "AOSP on IA Emulator",
        "deviceManufacturer": "Google"
      }
    }

**Comment by Demetresko** [comment]
and final 

V/MobileMessaging: CREATE INSTALLATION DONE <<<
    {
      "appVersion": "8.3.2451.debug",
      "deviceManufacturer": "Google",
      "deviceModel": "AOSP on IA Emulator",
      "deviceName": "AOSP on IA Emulator",
      "deviceSecure": false,
      "deviceTimezoneOffset": "GMT+03:00",
      "geoEnabled": false,
      "isPrimary": false,
      "language": "en",
      "notificationsEnabled": true,
      "os": "Android",
      "osVersion": "9",
      "pushRegId": "1183b67b-a9c5-473b-aa87-10e964956b6f",
      "regEnabled": true,
      "sdkVersion": "6.3.2"
    }

**Comment by riskpp** [comment]
Hello! one weird thing I've notice, the token for failed attempt looks very weird, you've provided it here
https://github.com/infobip/mobile-messaging-sdk-android/issues/33#issuecomment-1240597848

but for success attempts token looks ok (previous message for ex)

**Comment by Demetresko** [comment]
Seems like bug was on our side, thank u for ur help.
