### ISSUE TITLE
Closing keyboard when user clicks back arrow in a toolbar

### ISSUE THREAD

**Issue by p1nkydev** [infobip/mobile-messaging-sdk-android#36]
Could you add please to InAppChatFragment.closeChatPage() closing keyboard. Otherwise activity that called InAppChatActivity will have keyboard opened on it. Same relevant for Huawei.

**Comment by jakubdzubak1** [comment]
Hi, we will fix it in next release. Thank you.

**Comment by jakubdzubak1** [comment]
Hi @p1nkydev, fixed in version 7.6.1
