### ISSUE TITLE
In-app chat errors handling improvement 

### ISSUE THREAD

**Issue by jakubdzubak1** [infobip/mobile-messaging-sdk-android#39]
Current error handling in In-app chat is not very user friendly. Very often user can see JSON as string and even full message is not visible. Length of message is limited to 2 rows of snackbar. See attached screenshot.
![MicrosoftTeams-image (5)](https://github.com/infobip/mobile-messaging-sdk-android/assets/48893948/8c968979-2cc2-419b-a37d-889bd5eda738)

AC: Improve error handling to achieve better UX.

**Comment by jakubhricik** [comment]
Hi, can you please assigne me to this issue?

**Comment by jakubdzubak1** [comment]
The improvement released as version [11.1.2](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/11.1.2), closing the issue.
