### ISSUE TITLE
java.lang.NoClassDefFoundError: org.infobip.mobile.messaging.platform.MobileMessagingJobService on android 4.4.2

### ISSUE THREAD

**Issue by lyricsking** [infobip/mobile-messaging-sdk-android#4]
Am trying to implement push notification in my app but i cant seem to get it to work on. Am currently testing on android 4.4.2. i understand the api level may not support JobService as the class definition itself includes the line `@TargetApi(24)
public class MobileMessagingJobService extends JobService { ...}.`
This occur in the build method trying to initialize the push Notification sdk like `new MobileMessaging.Builder(ApplicationContext.application)
                .withoutCarrierInfo()
                .withoutSystemInfo()
                .withoutStoringUserData()
                .withMessageStore(MyMessageStore.class)
                .build();`
 The output error is below:
`java.lang.NoClassDefFoundError: org.infobip.mobile.messaging.platform.MobileMessagingJobService
        at org.infobip.mobile.messaging.util.ComponentUtil.verifyManifestComponentsForPush(ComponentUtil.java:89)
        at org.infobip.mobile.messaging.MobileMessagingCore$Builder.build(MobileMessagingCore.java:1379)
        at org.infobip.mobile.messaging.MobileMessaging$Builder.build(MobileMessaging.java:676)`.
I need help on this urgently, any help will e greatly appreciated.

**Comment by tjuric** [comment]
Hi @lyricsKING, thank you for pointing it out. This is a bug that will be fixed today and released within new version. I'll give you a notice on this thread after release.
Good thing is that this exception is thrown only for your debug version and logged for release version of app, so if you had release version, this wouldn't crash, but log exception (which shouldn't have been there in the first place - but this will be fixed).

**Comment by lyricsking** [comment]
thanks, i would wait in anticipation.

**Comment by tjuric** [comment]
Bugfix is released within [1.14.13](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/1.14.13) version of MM SDK. Please, check if your issue is fixed so that you'll be able to work.

**Comment by lyricsking** [comment]
Thanks for the quick response, howvever I still have the same error and it points to this:
` if (Build.VERSION_CODES.N >= Build.VERSION.SDK_INT) {
            verifyManifestService(context, MobileMessagingJobService.class);
        } else {
            verifyManifestReceiver(context, MobileMessagingConnectivityReceiver.class);
        }`
i think it should be like `if (Build.VERSION_CODES.N <= Build.VERSION.SDK_INT) {
            verifyManifestService(context, MobileMessagingJobService.class);
        } else {
            verifyManifestReceiver(context, MobileMessagingConnectivityReceiver.class);
        }`

**Comment by tjuric** [comment]
There was an issue with condition. New version is up [1.14.14](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/1.14.14). Sorry for the inconvenience.

**Comment by lyricsking** [comment]
Much thanks

**Comment by tjuric** [comment]
You're welcome. I'll close the issue.
