### ISSUE TITLE
In-app-Notification Action click listener

### ISSUE THREAD

**Issue by Faiz882** [infobip/mobile-messaging-sdk-android#40]
Hey 
I have added **`NotificationTappedReceiver`** but it is working only for banner notification. How I can achieve in `modal` **in-app-notification** .  unable to find click listener for both actions open/close.

**Comment by tjuric** [comment]
Hi @Faiz882,

did you try to subscribe to NOTIFICATION_ACTION_TAPPED event described [here](https://github.com/infobip/mobile-messaging-sdk-android/wiki/Interactive-notifications#notification-action-custom-handling) and [here](https://github.com/infobip/mobile-messaging-sdk-android/wiki/Library-events#notification_action_tapped) as a library event?

**Comment by Faiz882** [comment]
Hi @tjuric 
As you can see in attached SS. I have already implemented this event as I mentioned in above comment it is working in banner notification but it's not working in `Modal` case 
![image](https://github.com/infobip/mobile-messaging-sdk-android/assets/29184029/960f9f3d-df1b-4559-90fe-304b3236e5ac)

**Comment by Faiz882** [comment]
Hi @tjuric 
Thanks for your reply and issue has been resolved by adding `org.infobip.mobile.messaging.interactive.NOTIFICATION_ACTION_TAPPED`

**Comment by tjuric** [comment]
I don't see one thing from your code, and it's the exact event you're subscribing to. We have two events that have really similar name: `org.infobip.mobile.messaging.NOTIFICATION_TAPPED` and `org.infobip.mobile.messaging.interactive.NOTIFICATION_ACTION_TAPPED`. 

Can you confirm that you subscribed to the `org.infobip.mobile.messaging.interactive.NOTIFICATION_ACTION_TAPPED` and not `org.infobip.mobile.messaging.NOTIFICATION_TAPPED` event?

**Comment by tjuric** [comment]
Sorry, I didn't see your response before I sent mine. Nice to see that you solved it!

BR,
Tereza

**Comment by Faiz882** [comment]
> Sorry, I didn't see your response before I sent mine. Nice to see that you solved it!
> 
> BR, Tereza

Once again thanks for your quick support.
