### ISSUE TITLE
Support for custom Android notification channels

### ISSUE THREAD

**Issue by sebastiangrg** [infobip/mobile-messaging-sdk-android#44]
Hello,

We noticed that infobip-mobile-messaging-android-sdk/src/main/java/org/infobip/mobile/messaging/MobileMessagingCore.java creates 2 Android notification channels by default ("mm_default_channel_high_priority" and "mm_default_channel").

We would like to be able to use custom Android notification channels based on our business requirements. So far we only managed to add new channels via the NotificationManager.

1. Is there a way to create additional channels through the SDK?
2. Is there a way to specify which channel to use, when using the "Send single Push notification" API ([Docs](https://www.infobip.com/docs/api/channels/mobile-app-messaging/send-single-push-notification))? Firebase allows this via the "android_channel_id" field ([Firebase Docs](https://firebase.google.com/docs/cloud-messaging/http-server-ref)). This is crucial, as most apps nowadays define their own custom channels which allow the user to configure which kind of notifications they are interested in.

**Comment by alboldy-ib** [comment]
Hello there,

Infobip uses profiling approach instead: there are multiple different options for audience segmentation, not bound to FCM alone, but can be freely used for APNS and HMS devices, as well as for other communication channels. These are being managed either per installation identity or per Person profile (which can include multiple installations of the same user at the same time).
You can find targeting options for Push API here - [docs](https://www.infobip.com/docs/mobile-app-messaging/send-mobile-app-messages-over-api) , and management of such attributes is described [here](https://www.infobip.com/docs/mobile-app-messaging/mobile-audience-profiling#preferences-and-subscriptions)
As well as creation of different scenarios using user-friendly web-interface - [documentation](https://www.infobip.com/docs/people/manage-audience#segments)

As a result, you can achieve the same - by managing either person-level or device-level subscriptions, and giving the end-user an option to manage them within the app.

Hope this helps, in case you need help with implementation - feel free to contact your account manager.

**Comment by riskpp** [comment]
Since no new questions or comments appeared in this thread, I'll close the issue. Could be reopened if needed.
