### ISSUE TITLE
Crash on MobileMessagingCore.getSyncMessagesIds

### ISSUE THREAD

**Issue by Pxinxs365** [infobip/mobile-messaging-sdk-android#45]
Hello Infobip team

I have got a crash in Crashlytics which goes from Infobip Android library. 
The current version of the lib `com.infobip.infobip-mobile-messaging-android-sdk` in a project is `11.1.2`. In addition `com.infobip.infobip-mobile-messaging-android-geo-sdk` lib is also used with the same version.

It happens from version to version. Please, let me know if more details are needed.

**Details from the Crashlitycs:**

Devices:
73% - LGE
27% - Samsung

Operating systems:
74% - Android 8
26% - Android 6

Device states:
95% - In background

### MobileMessagingCore.getSyncMessagesIds
java.lang.ArrayIndexOutOfBoundsException - length=1; index=1

org.infobip.mobile.messaging
MobileMessagingCore.java:711

Fatal Exception: java.lang.RuntimeException
An error occurred while executing doInBackground()

Caused by java.lang.ArrayIndexOutOfBoundsException
length=1; index=1

### Stack trace:

org.infobip.mobile.messaging.MobileMessagingCore.getSyncMessagesIds (MobileMessagingCore.java:719)
org.infobip.mobile.messaging.MobileMessagingCore.isMessageAlreadyProcessed (MobileMessagingCore.java)
org.infobip.mobile.messaging.cloud.MobileMessageHandler.handleMessage (MobileMessageHandler.java:52)
org.infobip.mobile.messaging.cloud.MobileMessagingCloudHandler.handleMessage (MobileMessagingCloudHandler.java:90)
org.infobip.mobile.messaging.cloud.MobileMessagingCloudHandler.handleWork (MobileMessagingCloudHandler.java:44)
org.infobip.mobile.messaging.cloud.MobileMessagingCloudService.onHandleWork (MobileMessagingCloudService.java)
org.infobip.mobile.messaging.platform.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:415)
org.infobip.mobile.messaging.platform.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:405)
android.os.AsyncTask$2.call (AsyncTask.java:295)

**Comment by ikresicc** [comment]
Hello @Pxinxs365 ,

can you try to update to new version of the lib: 12.6.2

If it happens again, we will need more info about bug environment conditions in order to reproduce it on our side.

**Comment by riskpp** [comment]
Closing it due to inactivity, feel free to reopen if needed.
