### ISSUE TITLE
How to set color in notification setting

### ISSUE THREAD

**Issue by kavathiyamahesh** [infobip/mobile-messaging-sdk-android#5]
Hello,

I want to use color for notification icon, so how can we set color?
Is there any way where I can override NotificationCompat to show my own style of notification

**Comment by stanislavin** [comment]
Hi, currently we don't have this supported. You have an option to handle this broadcast: https://github.com/infobip/mobile-messaging-sdk-android/wiki/Events#message_received and then create whichever notification you want.

Also, we will gladly accept a Pull request if you create one with this new feature.
