### ISSUE TITLE
How can I integrate this SDK in a ReactNative proejct?

### ISSUE THREAD

**Issue by harikrishnanp** [infobip/mobile-messaging-sdk-android#8]
I have tried integrating this SDK in a ReactNative project. But getting the below error:

`> Task :app:compileDebugJavaWithJavac FAILED
/Users/test/Documents/Projects/rnprototype_native/android/app/src/main/java/com/rnprototype/MainActivity.java:20: error: cannot find symbol
        setContentView(R.layout.activity_main);
                               ^
  symbol:   variable activity_main
  location: class layout

/Users/test/Documents/Projects/rnprototype_native/android/app/src/main/java/com/rnprototype/MainActivity.java:23: error: package MobileMessaging does not exist
                .Builder(getApplication())`

**MainActivity.java**

`package com.rnprototype;

import com.facebook.react.ReactActivity;
import android.os.Bundle;
import com.rnprototype.R;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "rnprototype";
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        new MobileMessaging
                .Builder(getApplication())
                .build();
    }
}`

**Comment by stanislavin** [comment]
Hi @harikrishnanp, since react native integration is not supported now out of the box, you will have to wrap MobileMessaging as NativeModule as described here: https://facebook.github.io/react-native/docs/native-modules-android.html

https://stackoverflow.com/questions/50270672/how-to-import-android-gradle-dependencies-in-react-native

and don't forget to link the library in gradle file for android platform of the app.

**Comment by harikrishnanp** [comment]
@stanislavin  Thank you for the quick reply. Let me try that.

**Comment by stanislavin** [comment]
Closing, will reopen if needed

**Comment by latusdenis** [comment]
@harikrishnanp Did it help? I am facing the same issue

**Comment by harikrishnanp** [comment]
Yes. I'm working on it. I couldn't build it successfully yet.

**Comment by tarunasharma089** [comment]
Its failing in proguard, what are the rules?

**Comment by kostap13** [comment]
@tarunasharma089  hi,
Maybe this plugin will help you:
https://github.com/infobip/mobile-messaging-react-native-plugin

**Comment by tarunasharma089** [comment]
@kostap13  plugin is fine, but it fails when proguard in android is enabled,
